import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Sora, Inter } from "next/font/google";

const sora = Sora({ subsets: ["latin"], variable: "--font-display", weight: ["600", "700"] });
const inter = Inter({ subsets: ["latin"], variable: "--font-body" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <html lang="en" className={`${sora.variable} ${inter.variable}`}>
      <body className="font-body bg-[#FAF8F3] text-[#202426]">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
